# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "my_custom_build"
  my_custom_build:
    # The type of runner that the job will run on
    name: Build Workflow
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Start Workflow Message Display
        run: echo Beginning the Custom Workflow Build!

      # Runs a single command using the runners shell
      - name: Install Packages
        run:  yarn install

      # Runs a single command using the runners shell
      - name: Build Packages
        run:  yarn run build
        
     # Runs a single command using the runners shell
      - name: Test Cases
        run:  yarn run test --coverage
        
     # Runs a single command using the runners shell
      - name: Test Cases
        run:  yarn fix-lint
